### ISSUE TITLE
Useless = if value is the empty string

### ISSUE THREAD

**Issue by zdm** [kazeburo/WWW-Form-UrlEncoded-XS#2]
Hello.

```
use WWW::Form::UrlEncoded::XS;

print WWW::Form::UrlEncoded::XS::build_urlencoded( a => '', a => 1, b => 2 );
```

will print:

```
a=&a=1&b=2
```

but expected:

```
a&a=1&b=2
```

If the value for some key is the empty string - the "=" sign is useless.

**Comment by kazeburo** [comment]
This issue may be fixed.
Add test
https://github.com/kazeburo/WWW-Form-UrlEncoded-XS/commit/233e12872bee8ecf38177634c440dd8e44dba24a
